config/routes.rb
Alpha1::Application.routes.draw do
  get "sessions/new"
  root to: "static#home"

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :shouts

  match '/signout', to: 'sessions#destroy', via: 'delete'
  get '/signin', to: 'sessions#new'
  get '/yellbox', to: 'shouts#index'

end

app/models/shout.rb
class Shout < ActiveRecord::Base
  belongs_to :user
  validates :body, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

	has_many :shouts

	before_save { self.email = email.downcase }
	before_save :create_remember_token

	validates :mtgname, presence: true
	validates :realname, presence: true
	validates :email, presence: true,
	                  format: { with: VALID_EMAIL_REGEX }
	has_secure_password
	validates :password_confirmation, presence: true
	validates :password, length: { minimum: 6 }


	private
		def create_remember_token
			self.remember_token = SecureRandom.urlsafe_base64
		end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_mtgname(params[:session][:mtgname])
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_back_or user
    else
    	@errors = ['Invalid mortragian/password combination']
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end
end

app/controllers/shouts_controller.rb
class ShoutsController < ApplicationController

	# Controller method pre-filtering. Groups outlined below, too.
	# ------------------------------------------------------------

	before_filter :signed_in_user, only: [:new, :create]
	before_filter :correct_user, only: [:edit, :update, :destroy]


	# Viewing: no restrictions.
	# -------------------------

	def index
		@shouts = Shout.all
	end

	def show
		@shout = Shout.find(params[:id])
	end


	# Make new shouts: must be signed_in_user.
	# ----------------------------------------

	def new
		@shout = Shout.new #(who: current_user)
	end

	def create
		@shout = current_user.shouts.build(shout_params)
		if @shout.save
			redirect_to shouts_path
		else
			render 'new'
		end
	end


	# Deal with existing shouts: must be correct_user.
	# ------------------------------------------------

	def edit
		# TODO
	end

	def update
		# TODO
	end

	def destroy
		@shout.destroy
		redirect_to shouts_path
	end


	# Private helpers (before_filter's).
	# ----------------------------------

	private
		def shout_params
			params.require(:shout).permit(:body)
		end

		def correct_user
			@shout = current_user.shouts.find_by(id: params[:id])
			redirect_to root_path if @shout.nil?
		end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      render 'show'
    else
      render 'new'
    end
  end

  private
    def user_params
      params.require(:user).permit(:mtgname, :realname,
        :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title)
    base_title = "Mortrag"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end

end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    cookies.permanent[:remember_token] = user.remember_token
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user 
    @current_user ||= User.find_by_remember_token(cookies[:remember_token])
  end

  def current_user?(user)
    user == current_user
  end

  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_url, notice: "Please sign in."
    end
  end

  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url
  end
end

app/helpers/shouts_helper.rb
module ShoutsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<div class="contents">
	&copy; 2013 Mortrag --- As many rights as we can reserve, reserved.
</div>

app/views/layouts/_header.html.erb
<div class="row">
	<div class="span3 mtg">
		<h1>
			<%= link_to raw("Mortrag<sub>&alpha;</sub>"), root_path%>
		</h1>
	</div>
</div>
<div class="row">
	<div class="span5 offset3 right">
		<% if signed_in? %>
			<%= current_user.mtgname %> | 
			<%= link_to "signout", signout_path, method: "delete" %>
		<% else %>
			<%= link_to "signin", signin_path %>
		<% end %>
	</div>
</div>

app/views/layouts/_leftbar.html.erb
Left bar whee

app/views/layouts/_rightbar.html.erb
Right bar whee

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
	<div class="container">
		<div class="row">
			<div class="span8 offset2 header">
				<%= render 'layouts/header' %>
			</div>
		</div>
		<div class="row">
			<div class="span2 leftbar">
				<%= render 'layouts/leftbar' %>
			</div>
			<div class="span8 mainbar">
				<div class="content">
					<%= yield %>
				</div>
			</div>
			<div class="span2 rightbar">
				<%= render 'layouts/rightbar' %>
			</div>
		</div>
		<div class="row">
			<div class="span8 offset2 footer">
				<%= render 'layouts/footer' %>
				<%= debug(params) if Rails.env.development? %>
			</div>
		</div>		
	</div>
</body>
</html>

app/views/shared/_errors.html.erb
<% if errors && errors.any? %>
	<div class="alert alert-error">
		Looks like you had a couple problems:
		<ul>
			<% errors.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</ul>
	</div>
<% end %>

app/views/shouts/edit.html.erb
No editing yet!

app/views/shouts/index.html.erb
<% provide :title, "Shouts" %>
<h1>Yellbox!</h1>
<% @shouts.each do |shout| %>
	<h2><%= word_wrap(shout.body) %></h2>
	<div class="author">
		--<%= shout.user.mtgname %>
		<% if current_user?(shout.user) then %>
			<div class="btn-group">
				<a class="btn btn-mini dropdown-toggle"
				   data-toggle="dropdown"
				   href="#"><span class="caret"></span></a>
				<ul class="dropdown-menu">
					<li>
						<%= link_to edit_shout_path(shout) do %>
							<i class="icon-pencil"></i> edit
						<% end %>
					</li>
					<li>
						<%= link_to shout_path(shout), method: "delete" do %>
							<i class="icon-trash"></i> remove
						<% end %>
					</li>
				</ul>
			</div>
		<% end %>
	</div>
<% end %>
<%= link_to "Make yourself heard", new_shout_path %>

app/views/shouts/new.html.erb
<% provide :title, "New shout" %>
<h1>Shout below</h1>
<%= render 'shared/errors', errors: @shout.errors.full_messages %>
<%= form_for(@shout) do |f| %>
	<%= f.label :body %>
	<%= f.text_area :body, style: "width: 90%"%>
	
	<br />
	<%= f.submit "Shout", class: "btn" %>
<% end %>

app/views/shouts/show.html.erb
This is a shoutout!

<%= @shout %>

app/views/users/index.html.erb
<% @users.each do |user| %>
<%=	user.mtgname + " -- " + user.realname %>
<% end %>

app/views/users/new.html.erb
<h1>Create a new MortragAlpha1 account</h1>

<%= render 'shared/errors', errors: @user.errors.full_messages %>

<%= form_for(@user) do |f| %>

<%= f.label :realname , "Name" %>
<%= f.text_field :realname %>

<%= f.label :email %>
<%= f.text_field :email %>

<%= f.label :mtgname, "Mortrag alias" %>
<%= f.text_field :mtgname %>

<%= f.label :password %>
<%= f.password_field :password %>

<%= f.label :password_confirmation %>
<%= f.password_field :password_confirmation %>
<br />
<%= f.submit "Sign up", class: "btn" %>

<% end %>

app/views/users/show.html.erb
<%=	@user.mtgname + " -- " + @user.realname %>